# Generated by Django 2.1.1 on 2018-09-08 11:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'academic'), ('sports', 'sports'), ('music', 'music')], max_length=20)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('academic', 'academic'), ('sports', 'sports'), ('music', 'music')], max_length=20)),
                ('level', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'localities',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('academic', 'academic'), ('sports', 'sports'), ('music', 'music')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Mr', 'Mr'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Ms', 'Ms'), ('Dr', 'Dr'), ('Prof', 'Prof'), ('Rev', 'Rev'), ('Hon', 'Hon'), ('Sir', 'Sir'), ('Ing', 'Ing')], max_length=10)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=120)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('bio', models.TextField()),
                ('tel', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits long.', regex='^\\d{8}$')], verbose_name='Telephone')),
                ('mob', models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Phone number must be exactly 8 digits long.', regex='^\\d{8}$')], verbose_name='Mobile')),
                ('email', models.EmailField(max_length=254)),
                ('locality', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Locality')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level'),
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tutor'),
        ),
    ]
