# Generated by Django 2.1.1 on 2018-09-20 09:21

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('review_text', models.TextField()),
                ('review_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='tutor',
            old_name='bio',
            new_name='bio1',
        ),
        migrations.AddField(
            model_name='tutor',
            name='bio2',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='bio3',
            field=models.TextField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='profile_pic',
            field=models.ImageField(default='lol.jpg', upload_to=app.models.Tutor.path_and_filename),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Tutor'),
        ),
    ]
