# Generated by Django 2.1.1 on 2018-09-20 11:24

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180920_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorGalleryPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to=app.models.TutorGalleryPic.path_and_filename)),
                ('tutor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='images', to='app.Tutor')),
            ],
        ),
    ]
