# Generated by Django 2.1.1 on 2018-09-20 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tutorgallerypic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorgallerypic',
            old_name='tutor_id',
            new_name='tutor',
        ),
    ]
