# Generated by Django 2.1.1 on 2018-11-25 14:11

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180920_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=app.models.Tutor.path_and_filename),
        ),
    ]
